### ISSUE TITLE
Missing POM files

### ISSUE THREAD

**Issue by eaglep91** [deeplearning4j/ComputerVision-examples#5]
Hi, I know this is prob a stupid question but I have to ask it here and search for help.

I'm cloning it with git and make it into my eclipse project with command "mvn eclipse:eclipse", but always it shows to me missing pom files, mainly from the "deepleanring4j", "nd4j" and "canova" these 3 packages. I saw it's trying to downloading the later version than what I have now. But I just got stucked about these stuffs in maven, which file should I modify or where should I go to download those .jars? The snapshot version are something I can't even locate in the maven reporsitory, sorry this is prob really stupid but I need to fix it and can't wait to test it on my image sets.

Any helps appreciated!

**Comment by agibsonccc** [comment]
This isn't a question for this repo. Go learn maven first:
https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html
